name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: # Trigger on tags like v1.0.0
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and tag the Docker image
      run: |
        VERSION=${{ github.ref_name }}  
        EPOCH=$(date +%s)  # Generate epoch timestamp
        IMAGE_NAME=dev4w4n/emasjid-maintenance-${VERSION}-${EPOCH}
        docker build -t emasjid-maintenance .
        docker tag emasjid-maintenance $IMAGE_NAME
        docker push $IMAGE_NAME
