name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags: # Trigger on tags like v1.0.0
      - "v*.*.*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out the code
      uses: actions/checkout@v4

    # Step 2: Log in to Docker Hub using username and password
    - name: Log in to Docker Hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build and tag the Docker image
    - name: Build and tag the Docker image
      run: |
        VERSION=${{ github.ref_name }}  # Extract the tag name (e.g., v1.0.0)
        EPOCH=$(date +%s)  # Generate epoch timestamp
        IMAGE_NAME=dev4w4n/emasjid-maintenance-${VERSION}-${EPOCH}
        
        docker build . --file Dockerfile --tag $IMAGE_NAME

    # Step 4: Push the Docker image to Docker Hub
    - name: Push the Docker image to Docker Hub
      run: |
        VERSION=${{ github.ref_name }}  # Extract the tag name (e.g., v1.0.0)
        EPOCH=$(date +%s)  # Generate epoch timestamp
        IMAGE_NAME=dev4w4n/emasjid-maintenance-${VERSION}-${EPOCH}
        
        docker push $IMAGE_NAME
